# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='MAC Address')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('external_network_address', models.GenericIPAddressField(blank=True, null=True)),
                ('network_address', models.GenericIPAddressField(blank=True, null=True)),
                ('online_since', models.DateTimeField(blank=True, null=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
