# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensors', '0002_load_initial_data'),
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('address_line_one', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'deployment_photos', verbose_name='Header Image')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('layer', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['sensor'],
                'verbose_name_plural': 'Deployment Sensors',
            },
        ),
        migrations.AddField(
            model_name='deploymentsensor',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='deployments.Deployment'),
        ),
        migrations.AddField(
            model_name='deploymentsensor',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensor'),
        ),
        migrations.AddField(
            model_name='deploymentannotation',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.Deployment'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='hub',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubs.Hub'),
        ),
        migrations.AlterUniqueTogether(
            name='deploymentsensor',
            unique_together=set([('deployment', 'sensor')]),
        ),
    ]
