# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='boiler_efficiency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='boiler_manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='boiler_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='boiler_output',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='building_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='building_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='building_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deploymentsensor',
            name='room_height',
            field=models.FloatField(default=2.4),
        ),
        migrations.AddField(
            model_name='deploymentsensor',
            name='room_length',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deploymentsensor',
            name='room_width',
            field=models.FloatField(default=0),
        ),
    ]
