# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-05 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_auto_20170419_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='building_length',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='building_width',
        ),
        migrations.AddField(
            model_name='deployment',
            name='boiler_thermostat',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='deployment',
            name='boiler_type',
            field=models.IntegerField(choices=[(1, 'Gas'), (2, 'Electric')], default=1),
        ),
        migrations.AddField(
            model_name='deployment',
            name='building_area',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deploymentsensor',
            name='nearest_thermostat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='building_height',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='deploymentsensor',
            name='room_length',
        ),
        migrations.RemoveField(
            model_name='deploymentsensor',
            name='room_width',
        ),
        migrations.AddField(
            model_name='deploymentsensor',
            name='room_area',
            field=models.FloatField(default=0),
        ),
    ]
