# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 13:50
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations

fixture = 'initial_data'

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='sensors')


def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    sensor_model = apps.get_model("sensors", "Sensor")
    sensor_model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
